### ISSUE TITLE
App crash when using lib in multiple instances 

### ISSUE THREAD

**Issue by skybind2020** [fabiosassu/StackExpandableView#4]
Used this in two activities and I see below crash  
on 2.1.0 or 2.1.1 constraintlayout

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.constraintlayout.motion.widget.MotionScene$Transition androidx.constraintlayout.motion.widget.MotionScene.getTransitionById(int)' on a null object reference
        at androidx.constraintlayout.motion.widget.MotionLayout.getTransition(MotionLayout.java:4717)
        at it.fabiosassu.stackexpandableview.StackExpandableView.rebuildTransition(StackExpandableView.kt:127)
2021-11-07 13:09:51.223 3064-3064/? E/AndroidRuntime:     at it.fabiosassu.stackexpandableview.StackExpandableView.redraw(StackExpandableView.kt:123)
        at it.fabiosassu.stackexpandableview.StackExpandableView.setOrientation(StackExpandableView.kt:24)
        at it.fabiosassu.stackexpandableview.StackExpandableView.init(StackExpandableView.kt:67)
        at it.fabiosassu.stackexpandableview.StackExpandableView.<init>(StackExpandableView.kt:43)

**Comment by fabiosassu** [comment]
The crash was related to the `Scene` object being `null` in the 2.1.x versions of the `MotionLayout`. I've fixed the issue and published the 1.0.1 update. Let me know if it fixes the issue for you!
